# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SpaceXFanApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpaceXFanApplication


  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher', '~> 5.0'
  pod 'SVProgressHUD'


end
